In [1]:
import pandas as pd
import matplotlib.pyplot as plt

data = pd.read_csv('NetFLixDATASET - Sheet1 (3).csv')
data.head()

Country      Continent  GrossNationalIncome  AlcoholConsumptionRate  \
0  Argentina  South America                21190                     8.3   
1  Australia        Oceania                48085                    10.4   
2    Austria         Europe                56197                     9.7   
3    Belgium         Europe                52085                    10.5   
4    Bolivia  South America                 8554                     3.8   

   HappinessScore  
0           5.929  
1           7.183  
2           7.268  
3           6.834  
4           5.716

In [2]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61 entries, 0 to 60
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   Country                 61 non-null     object 
 1   Continent               61 non-null     object 
 2   GrossNationalIncome     61 non-null     int64  
 3   AlcoholConsumptionRate  61 non-null     float64
 4   HappinessScore          61 non-null     float64
dtypes: float64(2), int64(1), object(2)
memory usage: 2.5+ KB


In [3]:
 data.isnull().sum()

Country                   0
Continent                 0
GrossNationalIncome       0
AlcoholConsumptionRate    0
HappinessScore            0
dtype: int64

In [4]:
data["Continent"].unique()

array(['South America', 'Oceania', 'Europe', 'North America', 'Asia',
       'Africa'], dtype=object)

In [5]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data["Continent"] = le.fit_transform(data["Continent"])
data["Continent"].unique()

array([5, 4, 2, 3, 1, 0])

In [6]:
datafinal=data.drop("Country",axis=1)
X=datafinal.drop("HappinessScore",axis=1)
y=datafinal["HappinessScore"]

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=1)

In [8]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [9]:
from sklearn.metrics import mean_squared_error,mean_absolute_error
y_pred=model.predict(X_test)

In [10]:
from sklearn.tree import DecisionTreeRegressor
dtr=DecisionTreeRegressor(random_state=0)
dtr.fit(X_train,y_train)
y_pred=dtr.predict(X_test)

In [11]:

import numpy as np
error=np.sqrt(mean_squared_error(y_test,y_pred))
error

0.5784198302271456

In [12]:
from sklearn.ensemble import RandomForestRegressor
rfr=RandomForestRegressor(random_state=0)
rfr.fit(X_train,y_train)
y_pred=rfr.predict(X_test)

In [13]:
error2=np.sqrt(mean_squared_error(y_test,y_pred))
error2

0.3643466093828088

In [14]:
from sklearn.model_selection import GridSearchCV
max_depth=[None,2,4,6,8,10,12]
parameters={"max_depth":max_depth}

rg=RandomForestRegressor(random_state=0)
gs=GridSearchCV(rg,parameters,scoring='neg_mean_squared_error')
gs.fit(X_train,y_train)

GridSearchCV(estimator=RandomForestRegressor(random_state=0),
             param_grid={'max_depth': [None, 2, 4, 6, 8, 10, 12]},
             scoring='neg_mean_squared_error')

In [15]:
rg=gs.best_estimator_
rg.fit(X_train,y_train)
y_pred=rg.predict(X_test)
error=np.sqrt(mean_squared_error(y_test,y_pred))
error

0.3686109461522866

In [36]:
X=np.array([["Europe",30009,9.3]])
X

array([['Europe', '30009', '9.3']], dtype='<U32')

In [37]:

X[:,0]=le.transform(X[:,0])
X=X.astype(float)
X

array([[2.0000e+00, 3.0009e+04, 9.3000e+00]])

In [38]:
y_pred=rg.predict(X)
y_pred[0]

/Users/meena/opt/anaconda3/envs/ml/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


5.889767805038207

In [39]:
import pickle
data1={"model":rg,"le":le}
with open('saved_steps.pkl','wb') as file:
    pickle.dump(data1,file)

In [40]:
with open('saved_steps.pkl','rb') as file:
    data1=pickle.load(file)
regressor_loaded=data1["model"]
le=data1["le"]


In [41]:
y_pred=regressor_loaded.predict(X)
y_pred

/Users/meena/opt/anaconda3/envs/ml/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([5.88976781])